import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

async function source(path) {
  return readFile(new URL(`../${path}`, import.meta.url), "utf8");
}

const [
  businessCopy,
  print,
  sessionPrint,
  sessionWord,
  sessionMarkdown,
  dashboard,
  market,
  productTrial,
  orderSlip,
  orderCsv,
  marketCsv,
  sessionCsv,
  followupCsv,
  testCsv,
  routeCustomerCsv,
  missingGpsCsv,
  csv,
  exportErrors,
  exportLinks
] = await Promise.all([
  source("src/lib/export/business-report.ts"),
  source("src/lib/export/print.ts"),
  source("src/app/api/pdf/session-day/route.ts"),
  source("src/app/api/mcp-session-report/word/route.ts"),
  source("src/lib/mcp/session-report-export-v2.ts"),
  source("src/app/api/pdf/dashboard/route.ts"),
  source("src/app/api/pdf/market-report/route.ts"),
  source("src/app/api/pdf/test-result/route.ts"),
  source("src/app/api/pdf/order-slip/route.ts"),
  source("src/app/api/exports/orders.csv/route.ts"),
  source("src/app/api/exports/market-reports.csv/route.ts"),
  source("src/app/api/exports/mcp-sessions.csv/route.ts"),
  source("src/app/api/exports/followups.csv/route.ts"),
  source("src/app/api/exports/tests.csv/route.ts"),
  source("src/app/api/exports/route-customers.csv/route.ts"),
  source("src/app/api/exports/route-customers-needs-gps.csv/route.ts"),
  source("src/lib/export/csv.ts"),
  source("src/lib/export/supabase-rest.ts"),
  source("src/features/exports/ExportLinks.tsx")
]);

test("reader reports use Vietnamese business titles instead of developer copy", () => {
  assert.match(sessionPrint, /Báo cáo kết quả phiên bán hàng/);
  assert.match(sessionWord, /Báo cáo kết quả phiên bán hàng/);
  assert.match(dashboard, /Báo cáo điều hành bán hàng/);
  assert.match(market, /Báo cáo thị trường và cơ hội bán hàng/);
  assert.match(productTrial, /Phiếu kết quả thử sản phẩm/);
  assert.match(orderSlip, /Phiếu xác nhận đơn hàng/);

  for (const report of [sessionPrint, sessionWord, dashboard, market, productTrial, orderSlip]) {
    assert.doesNotMatch(report, /Dashboard quản trị|BC phiên|XUAT PHIEN|Checklist|Top SP\/brand|Next action|Cần truyền fileId|Generated by/i);
  }
});

test("session print keeps Vietnamese and no longer uses the ASCII-only PDF builder", () => {
  assert.match(sessionPrint, /htmlResponse/);
  assert.match(sessionPrint, /Điểm bán kế hoạch/);
  assert.match(sessionPrint, /Việc nên thực hiện tiếp theo/);
  assert.doesNotMatch(sessionPrint, /buildMcpSessionPdf|application\/pdf|TT|KQ|FU:/);
  assert.match(print, /In hoặc lưu PDF/);
  assert.match(print, /Báo cáo được lập lúc/);
});

test("readable Word and Markdown reports do not expose implementation metadata", () => {
  assert.doesNotMatch(sessionWord, /schemaVersion|Session ID|Snapshot|Health|Generated by|ID hệ thống/);
  const markdownBuilder = sessionMarkdown.split("export function buildSessionReportMarkdownV2")[1].split("export function sessionReportExportFilenameV2")[0];
  assert.match(markdownBuilder, /Nhận định chung/);
  assert.match(markdownBuilder, /Việc nên thực hiện tiếp theo/);
  assert.doesNotMatch(markdownBuilder, /Session ID|Schema|Snapshot|Health|Generated by|Kết quả AI đã lưu|```json/);
});

test("export status, priority, source, dates and filenames are centrally normalized", () => {
  assert.match(businessCopy, /confirmed: "Đã chốt"/);
  assert.match(businessCopy, /delivered: "Đã giao"/);
  assert.match(businessCopy, /high: "Cao"/);
  assert.match(businessCopy, /orders_tab: "Tạo tại màn Đơn"/);
  assert.match(businessCopy, /export function reportDate/);
  assert.match(businessCopy, /export function reportFilename/);
});

test("all primary CSV exports lead with business columns and translate technical headers", () => {
  const exports = [orderCsv, marketCsv, sessionCsv, followupCsv, testCsv, routeCustomerCsv, missingGpsCsv];
  for (const dataExport of exports) {
    assert.doesNotMatch(dataExport, /header: "Sale"|header: "Route ID"|header: "Session ID"|header: "Variant ID"|header: "Source ID"|header: "Sync"|header: "Next action"|header: "Lat"|header: "Lng"/);
  }
  assert.match(orderCsv, /header: "Nhân viên phụ trách"/);
  assert.match(orderCsv, /header: "Số lượng"/);
  assert.match(marketCsv, /header: "Hành động tiếp theo"/);
  assert.match(sessionCsv, /header: "Kết quả ghé"/);
  assert.match(followupCsv, /header: "Mức ưu tiên"/);
  assert.match(testCsv, /header: "Kết quả thử"/);
  assert.match(routeCustomerCsv, /header: "Tên tuyến"/);
  assert.match(routeCustomerCsv, /header: "Vĩ độ"/);
  assert.match(missingGpsCsv, /điem-ban-can-cap-nhat-vi-tri|diem-ban-can-cap-nhat-vi-tri/);
});

test("CSV files are safe to open in spreadsheet software", () => {
  assert.match(csv, /\^\[=\+\\-@\]/);
  assert.match(csv, /filename\*=UTF-8/);
  assert.match(csv, /X-Content-Type-Options/);
});

test("export failures show reader messages while preserving an internal code", () => {
  assert.match(exportErrors, /reportErrorMessage/);
  assert.match(exportErrors, /error: reportErrorMessage\(code\)/);
  assert.match(exportErrors, /code/);
});

test("export menus distinguish readable reports from operational data", () => {
  assert.match(exportLinks, /Dữ liệu Excel \/ CSV/);
  assert.match(exportLinks, /Báo cáo để đọc và in/);
  assert.match(exportLinks, /Báo cáo để đọc và gửi/);
  assert.match(exportLinks, /Bản in \/ PDF/);
  assert.match(exportLinks, /Bảng chi tiết Excel \/ CSV/);
  assert.match(exportLinks, /Chọn file cần xuất/);
  assert.doesNotMatch(exportLinks, /Excel dữ liệu|PDF báo cáo|Tải Excel nền/);
});
