param(
  [string]$ProjectRoot = "F:\1_A_Disk_D\Tool\mcp-plan",
  [switch]$CommitAndPush
)

$ErrorActionPreference = "Stop"

function Fail($message) {
  Write-Host ""
  Write-Host "ERROR: $message" -ForegroundColor Red
  exit 1
}

if (-not (Test-Path $ProjectRoot)) {
  Fail "Project root not found: $ProjectRoot"
}

Set-Location $ProjectRoot

$backendPath = Join-Path $ProjectRoot "apps\backend\server.js"
$pagePath = Join-Path $ProjectRoot "src\app\mcp\settings\page.tsx"
$migrationPath = Join-Path $ProjectRoot "supabase\migrations\20260705_mcp_route_order_template_contract.sql"

if (-not (Test-Path $backendPath)) { Fail "Backend file not found: $backendPath" }
if (-not (Test-Path $pagePath)) { Fail "Settings page not found: $pagePath" }

$backupDir = Join-Path $env:TEMP ("mcp-route-order-template-backup-" + (Get-Date -Format "yyyyMMdd-HHmmss"))
New-Item -ItemType Directory -Path $backupDir | Out-Null
Copy-Item $backendPath (Join-Path $backupDir "server.js.bak")
Copy-Item $pagePath (Join-Path $backupDir "page.tsx.bak")
Write-Host "Backup outside repo: $backupDir" -ForegroundColor Cyan

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)

$migrationBase64 = "LS0gUGhhc2UgQy4xIFJvdXRlIHNldHRpbmdzOiBvcmRlciB0ZW1wbGF0ZSBjb250cmFjdC4KLS0gT25lIGFjdGl2ZSBvcmRlciB0ZW1wbGF0ZSBwZXIgcm91dGUsIHdpdGggcmV1c2FibGUgdGVtcGxhdGUgaXRlbXMuCi0tIFVzZWQgYnkgL21jcC9zZXR0aW5ncyBiZWZvcmUgd2lyaW5nIHRlbXBsYXRlcyBpbnRvIG9yZGVyIGNyZWF0aW9uLgoKY3JlYXRlIHRhYmxlIGlmIG5vdCBleGlzdHMgcHVibGljLm1jcF9yb3V0ZV9vcmRlcl90ZW1wbGF0ZXMgKAogIGlkIHRleHQgcHJpbWFyeSBrZXksCiAgcm91dGVfaWQgdGV4dCBub3QgbnVsbCByZWZlcmVuY2VzIHB1YmxpYy5tY3Bfcm91dGVzKGlkKSBvbiBkZWxldGUgY2FzY2FkZSwKICB0aXRsZSB0ZXh0IG5vdCBudWxsIGRlZmF1bHQgJ01hdSBkb24gaGFuZycsCiAgc3RhdHVzIHRleHQgbm90IG51bGwgZGVmYXVsdCAnYWN0aXZlJywKICBub3RlIHRleHQsCiAgcmF3X3BheWxvYWQganNvbmIsCiAgY3JlYXRlZF9hdCB0aW1lc3RhbXB0eiBkZWZhdWx0IG5vdygpLAogIHVwZGF0ZWRfYXQgdGltZXN0YW1wdHogZGVmYXVsdCBub3coKSwKICB1bmlxdWUgKHJvdXRlX2lkKQopOwoKY3JlYXRlIHRhYmxlIGlmIG5vdCBleGlzdHMgcHVibGljLm1jcF9yb3V0ZV9vcmRlcl90ZW1wbGF0ZV9pdGVtcyAoCiAgaWQgdGV4dCBwcmltYXJ5IGtleSwKICB0ZW1wbGF0ZV9pZCB0ZXh0IG5vdCBudWxsIHJlZmVyZW5jZXMgcHVibGljLm1jcF9yb3V0ZV9vcmRlcl90ZW1wbGF0ZXMoaWQpIG9uIGRlbGV0ZSBjYXNjYWRlLAogIHByb2R1Y3RfaWQgdGV4dCwKICBwcm9kdWN0X25hbWUgdGV4dCBub3QgbnVsbCwKICBza3UgdGV4dCwKICB1bml0IHRleHQsCiAgcXVhbnRpdHkgbnVtZXJpYyBub3QgbnVsbCBkZWZhdWx0IDEsCiAgdW5pdF9wcmljZSBudW1lcmljIG5vdCBudWxsIGRlZmF1bHQgMCwKICBkaXNjb3VudCBudW1lcmljIG5vdCBudWxsIGRlZmF1bHQgMCwKICBzb3J0X29yZGVyIGludGVnZXIgbm90IG51bGwgZGVmYXVsdCAwLAogIG5vdGUgdGV4dCwKICByYXdfcGF5bG9hZCBqc29uYiwKICBjcmVhdGVkX2F0IHRpbWVzdGFtcHR6IGRlZmF1bHQgbm93KCksCiAgdXBkYXRlZF9hdCB0aW1lc3RhbXB0eiBkZWZhdWx0IG5vdygpCik7CgpjcmVhdGUgaW5kZXggaWYgbm90IGV4aXN0cyBtY3Bfcm91dGVfb3JkZXJfdGVtcGxhdGVfaXRlbXNfdGVtcGxhdGVfaWR4Cm9uIHB1YmxpYy5tY3Bfcm91dGVfb3JkZXJfdGVtcGxhdGVfaXRlbXModGVtcGxhdGVfaWQsIHNvcnRfb3JkZXIpOwoKY3JlYXRlIG9yIHJlcGxhY2UgZnVuY3Rpb24gcHVibGljLm1jcF9zYXZlX3JvdXRlX29yZGVyX3RlbXBsYXRlKAogIHBfcm91dGVfaWQgdGV4dCwKICBwX3RpdGxlIHRleHQgZGVmYXVsdCAnTWF1IGRvbiBoYW5nJywKICBwX25vdGUgdGV4dCBkZWZhdWx0IG51bGwsCiAgcF9pdGVtcyBqc29uYiBkZWZhdWx0ICdbXSc6Ompzb25iCikKcmV0dXJucyBqc29uYgpsYW5ndWFnZSBwbHBnc3FsCnNldCBzZWFyY2hfcGF0aCA9IHB1YmxpYwphcyAkJApkZWNsYXJlCiAgciByZWNvcmQ7CiAgdl90ZW1wbGF0ZV9pZCB0ZXh0OwogIGl0ZW0ganNvbmI7CiAgdl9wcm9kdWN0X25hbWUgdGV4dDsKICB2X3F1YW50aXR5IG51bWVyaWM7CiAgdl91bml0X3ByaWNlIG51bWVyaWM7CiAgdl9kaXNjb3VudCBudW1lcmljOwogIHZfc29ydCBpbnRlZ2VyIDo9IDA7CiAgdl9pdGVtX2NvdW50IGludGVnZXIgOj0gMDsKICBub3dfdHMgdGltZXN0YW1wdHogOj0gbm93KCk7CmJlZ2luCiAgaWYgcF9yb3V0ZV9pZCBpcyBudWxsIG9yIGxlbmd0aCh0cmltKHBfcm91dGVfaWQpKSA9IDAgdGhlbgogICAgcmFpc2UgZXhjZXB0aW9uICdyb3V0ZV9pZF9yZXF1aXJlZCcgdXNpbmcgZXJyY29kZSA9ICcyMzUxNCc7CiAgZW5kIGlmOwoKICBpZiBwX2l0ZW1zIGlzIG51bGwgb3IganNvbmJfdHlwZW9mKHBfaXRlbXMpIDw+ICdhcnJheScgb3IganNvbmJfYXJyYXlfbGVuZ3RoKHBfaXRlbXMpID0gMCB0aGVuCiAgICByYWlzZSBleGNlcHRpb24gJ3RlbXBsYXRlX2l0ZW1zX3JlcXVpcmVkJyB1c2luZyBlcnJjb2RlID0gJzIzNTE0JzsKICBlbmQgaWY7CgogIHNlbGVjdCBpZCwgcm91dGVfbmFtZSBpbnRvIHIKICAgIGZyb20gcHVibGljLm1jcF9yb3V0ZXMKICAgd2hlcmUgaWQgPSBwX3JvdXRlX2lkOwoKICBpZiByLmlkIGlzIG51bGwgdGhlbgogICAgcmFpc2UgZXhjZXB0aW9uICdyb3V0ZV9ub3RfZm91bmQnIHVzaW5nIGVycmNvZGUgPSAnMjM1MDMnOwogIGVuZCBpZjsKCiAgc2VsZWN0IGlkIGludG8gdl90ZW1wbGF0ZV9pZAogICAgZnJvbSBwdWJsaWMubWNwX3JvdXRlX29yZGVyX3RlbXBsYXRlcwogICB3aGVyZSByb3V0ZV9pZCA9IHIuaWQ7CgogIGlmIHZfdGVtcGxhdGVfaWQgaXMgbnVsbCB0aGVuCiAgICB2X3RlbXBsYXRlX2lkIDo9ICdtY3Bfb3JkZXJfdGVtcGxhdGVfJyB8fCByZXBsYWNlKGdlbl9yYW5kb21fdXVpZCgpOjp0ZXh0LCAnLScsICcnKTsKICAgIGluc2VydCBpbnRvIHB1YmxpYy5tY3Bfcm91dGVfb3JkZXJfdGVtcGxhdGVzICgKICAgICAgaWQsIHJvdXRlX2lkLCB0aXRsZSwgc3RhdHVzLCBub3RlLCByYXdfcGF5bG9hZCwgY3JlYXRlZF9hdCwgdXBkYXRlZF9hdAogICAgKSB2YWx1ZXMgKAogICAgICB2X3RlbXBsYXRlX2lkLAogICAgICByLmlkLAogICAgICBjb2FsZXNjZShudWxsaWYodHJpbShjb2FsZXNjZShwX3RpdGxlLCAnJykpLCAnJyksICdNYXUgZG9uIGhhbmcnKSwKICAgICAgJ2FjdGl2ZScsCiAgICAgIG51bGxpZih0cmltKGNvYWxlc2NlKHBfbm90ZSwgJycpKSwgJycpLAogICAgICBqc29uYl9idWlsZF9vYmplY3QoJ3NvdXJjZScsICdtY3Bfc2F2ZV9yb3V0ZV9vcmRlcl90ZW1wbGF0ZScpLAogICAgICBub3dfdHMsCiAgICAgIG5vd190cwogICAgKTsKICBlbHNlCiAgICB1cGRhdGUgcHVibGljLm1jcF9yb3V0ZV9vcmRlcl90ZW1wbGF0ZXMKICAgICAgIHNldCB0aXRsZSA9IGNvYWxlc2NlKG51bGxpZih0cmltKGNvYWxlc2NlKHBfdGl0bGUsICcnKSksICcnKSwgdGl0bGUsICdNYXUgZG9uIGhhbmcnKSwKICAgICAgICAgICBzdGF0dXMgPSAnYWN0aXZlJywKICAgICAgICAgICBub3RlID0gbnVsbGlmKHRyaW0oY29hbGVzY2UocF9ub3RlLCAnJykpLCAnJyksCiAgICAgICAgICAgdXBkYXRlZF9hdCA9IG5vd190cwogICAgIHdoZXJlIGlkID0gdl90ZW1wbGF0ZV9pZDsKCiAgICBkZWxldGUgZnJvbSBwdWJsaWMubWNwX3JvdXRlX29yZGVyX3RlbXBsYXRlX2l0ZW1zCiAgICAgd2hlcmUgdGVtcGxhdGVfaWQgPSB2X3RlbXBsYXRlX2lkOwogIGVuZCBpZjsKCiAgZm9yIGl0ZW0gaW4gc2VsZWN0IHZhbHVlIGZyb20ganNvbmJfYXJyYXlfZWxlbWVudHMocF9pdGVtcykgbG9vcAogICAgdl9wcm9kdWN0X25hbWUgOj0gbnVsbGlmKHRyaW0oY29hbGVzY2UoaXRlbSAtPj4gJ3Byb2R1Y3ROYW1lJywgaXRlbSAtPj4gJ3Byb2R1Y3RfbmFtZScsICcnKSksICcnKTsKICAgIGlmIHZfcHJvZHVjdF9uYW1lIGlzIG51bGwgdGhlbgogICAgICByYWlzZSBleGNlcHRpb24gJ3Byb2R1Y3RfbmFtZV9yZXF1aXJlZCcgdXNpbmcgZXJyY29kZSA9ICcyMzUxNCc7CiAgICBlbmQgaWY7CgogICAgdl9xdWFudGl0eSA6PSBjb2FsZXNjZShudWxsaWYoaXRlbSAtPj4gJ3F1YW50aXR5JywgJycpOjpudW1lcmljLCAxKTsKICAgIHZfdW5pdF9wcmljZSA6PSBjb2FsZXNjZShudWxsaWYoY29hbGVzY2UoaXRlbSAtPj4gJ3VuaXRQcmljZScsIGl0ZW0gLT4+ICd1bml0X3ByaWNlJyksICcnKTo6bnVtZXJpYywgMCk7CiAgICB2X2Rpc2NvdW50IDo9IGNvYWxlc2NlKG51bGxpZihpdGVtIC0+PiAnZGlzY291bnQnLCAnJyk6Om51bWVyaWMsIDApOwoKICAgIGlmIHZfcXVhbnRpdHkgPD0gMCB0aGVuCiAgICAgIHJhaXNlIGV4Y2VwdGlvbiAncXVhbnRpdHlfcmVxdWlyZWQnIHVzaW5nIGVycmNvZGUgPSAnMjM1MTQnOwogICAgZW5kIGlmOwogICAgaWYgdl91bml0X3ByaWNlIDwgMCBvciB2X2Rpc2NvdW50IDwgMCB0aGVuCiAgICAgIHJhaXNlIGV4Y2VwdGlvbiAnaW52YWxpZF9wcmljZV9vcl9kaXNjb3VudCcgdXNpbmcgZXJyY29kZSA9ICcyMzUxNCc7CiAgICBlbmQgaWY7CgogICAgdl9zb3J0IDo9IHZfc29ydCArIDE7CgogICAgaW5zZXJ0IGludG8gcHVibGljLm1jcF9yb3V0ZV9vcmRlcl90ZW1wbGF0ZV9pdGVtcyAoCiAgICAgIGlkLCB0ZW1wbGF0ZV9pZCwgcHJvZHVjdF9pZCwgcHJvZHVjdF9uYW1lLCBza3UsIHVuaXQsIHF1YW50aXR5LCB1bml0X3ByaWNlLAogICAgICBkaXNjb3VudCwgc29ydF9vcmRlciwgbm90ZSwgcmF3X3BheWxvYWQsIGNyZWF0ZWRfYXQsIHVwZGF0ZWRfYXQKICAgICkgdmFsdWVzICgKICAgICAgJ21jcF9vcmRlcl90ZW1wbGF0ZV9pdGVtXycgfHwgcmVwbGFjZShnZW5fcmFuZG9tX3V1aWQoKTo6dGV4dCwgJy0nLCAnJyksCiAgICAgIHZfdGVtcGxhdGVfaWQsCiAgICAgIG51bGxpZih0cmltKGNvYWxlc2NlKGl0ZW0gLT4+ICdwcm9kdWN0SWQnLCBpdGVtIC0+PiAncHJvZHVjdF9pZCcsICcnKSksICcnKSwKICAgICAgdl9wcm9kdWN0X25hbWUsCiAgICAgIG51bGxpZih0cmltKGNvYWxlc2NlKGl0ZW0gLT4+ICdza3UnLCAnJykpLCAnJyksCiAgICAgIG51bGxpZih0cmltKGNvYWxlc2NlKGl0ZW0gLT4+ICd1bml0JywgJycpKSwgJycpLAogICAgICB2X3F1YW50aXR5LAogICAgICB2X3VuaXRfcHJpY2UsCiAgICAgIHZfZGlzY291bnQsCiAgICAgIHZfc29ydCwKICAgICAgbnVsbGlmKHRyaW0oY29hbGVzY2UoaXRlbSAtPj4gJ25vdGUnLCAnJykpLCAnJyksCiAgICAgIGl0ZW0gfHwganNvbmJfYnVpbGRfb2JqZWN0KCdzb3VyY2UnLCAnbWNwX3NhdmVfcm91dGVfb3JkZXJfdGVtcGxhdGUnKSwKICAgICAgbm93X3RzLAogICAgICBub3dfdHMKICAgICk7CgogICAgdl9pdGVtX2NvdW50IDo9IHZfaXRlbV9jb3VudCArIDE7CiAgZW5kIGxvb3A7CgogIHJldHVybiBqc29uYl9idWlsZF9vYmplY3QoCiAgICAndGVtcGxhdGVJZCcsIHZfdGVtcGxhdGVfaWQsCiAgICAncm91dGVJZCcsIHIuaWQsCiAgICAncm91dGVOYW1lJywgci5yb3V0ZV9uYW1lLAogICAgJ2l0ZW1Db3VudCcsIHZfaXRlbV9jb3VudAogICk7CmVuZDsKJCQ7Cg=="
$migrationBytes = [Convert]::FromBase64String($migrationBase64)
[System.IO.File]::WriteAllBytes($migrationPath, $migrationBytes)
Write-Host "Wrote migration file" -ForegroundColor Green

$backend = [System.IO.File]::ReadAllText($backendPath, [System.Text.Encoding]::UTF8)

$templateHelpers = @'
function normalizeMcpOrderTemplateItems(items) {
  if (!Array.isArray(items) || items.length === 0) throw badRequest("template_items_required");

  return items.map((item) => {
    const productName = String(item.productName || item.product_name || "").trim();
    const quantity = Number(item.quantity || 0);
    const unitPrice = Number(item.unitPrice ?? item.unit_price ?? 0);
    const discount = Number(item.discount || 0);

    if (!productName) throw badRequest("product_name_required");
    if (!Number.isFinite(quantity) || quantity <= 0) throw badRequest("quantity_required");
    if (!Number.isFinite(unitPrice) || unitPrice < 0) throw badRequest("invalid_unit_price");
    if (!Number.isFinite(discount) || discount < 0) throw badRequest("invalid_discount");

    return {
      productId: String(item.productId || item.product_id || "").trim() || null,
      productName,
      sku: String(item.sku || "").trim() || null,
      unit: String(item.unit || "").trim() || null,
      quantity,
      unitPrice,
      discount,
      note: String(item.note || "").trim() || null
    };
  });
}

async function loadMcpOrderTemplateSettings(url) {
  const routes = await loadRoutes();
  const routeId = String(url.searchParams.get("routeId") || routes[0]?.id || "").trim();

  let template = null;
  if (routeId) {
    const templates = await supabaseGet("mcp_route_order_templates", {
      select: "id,route_id,title,note,status,updated_at",
      route_id: `eq.${routeId}`,
      limit: 1
    });

    const row = templates[0] || null;
    if (row) {
      const items = await supabaseGet("mcp_route_order_template_items", {
        select: "id,product_id,product_name,sku,unit,quantity,unit_price,discount,sort_order,note",
        template_id: `eq.${row.id}`,
        order: "sort_order.asc,created_at.asc",
        limit: 200
      });

      template = {
        id: row.id,
        routeId: row.route_id,
        title: row.title || "Mau don hang",
        note: row.note || "",
        items: items.map((item) => ({
          id: item.id,
          productId: item.product_id || "",
          productName: item.product_name || "",
          sku: item.sku || "",
          unit: item.unit || "",
          quantity: String(item.quantity ?? 1),
          unitPrice: String(item.unit_price ?? 0),
          discount: String(item.discount ?? 0),
          sortOrder: item.sort_order || 0,
          note: item.note || ""
        }))
      };
    }
  }

  return {
    routes: routes.map((route) => ({
      id: route.id,
      name: route.name,
      area: route.area,
      salesOwner: route.salesOwner,
      status: route.status
    })),
    selectedRouteId: routeId,
    template
  };
}

async function saveMcpOrderTemplateSettings(body) {
  const routeId = String(body.routeId || body.route_id || "").trim();
  if (!routeId) throw badRequest("route_id_required");

  const title = String(body.title || "").trim();
  const note = String(body.note || "").trim();
  const items = normalizeMcpOrderTemplateItems(body.items);

  return supabaseRpc("mcp_save_route_order_template", {
    p_route_id: routeId,
    p_title: title || "Mau don hang",
    p_note: note || null,
    p_items: items
  });
}

'@

if ($backend -notmatch "function normalizeMcpOrderTemplateItems") {
  $anchor = "`nfunction randomId(prefix)"
  $index = $backend.IndexOf($anchor)
  if ($index -lt 0) { Fail "Anchor function randomId(prefix) not found" }
  $backend = $backend.Substring(0, $index) + "`n" + $templateHelpers + $backend.Substring($index)
  Write-Host "Inserted backend order-template helpers" -ForegroundColor Green
} else {
  Write-Host "Backend order-template helpers already exist" -ForegroundColor Yellow
}

$getRoute = 'if (url.pathname === "/api/mcp-settings/order-template") return wrap(await loadMcpOrderTemplateSettings(url));'
if ($backend -notmatch '/api/mcp-settings/order-template') {
  $getAnchor = 'if (url.pathname === "/api/mcp-day/test-options") return wrap(await loadMcpTestOptions());'
  if (-not $backend.Contains($getAnchor)) { Fail "GET route anchor not found" }
  $backend = $backend.Replace($getAnchor, $getAnchor + "`n  " + $getRoute)
  Write-Host "Inserted GET /api/mcp-settings/order-template" -ForegroundColor Green
} else {
  Write-Host "Order-template GET route already exists" -ForegroundColor Yellow
}

$postRoute = 'if (url.pathname === "/api/mcp-settings/order-template") return wrap(await saveMcpOrderTemplateSettings(await readJsonBody(req)));'
if ($backend -notmatch 'saveMcpOrderTemplateSettings') {
  Fail "Order-template helper insert failed"
}
if (-not $backend.Contains($postRoute)) {
  $postAnchor = 'if (url.pathname === "/api/mcp-day/session-customer/followup") return wrap(await createMcpSessionCustomerFollowup(await readJsonBody(req)));'
  if (-not $backend.Contains($postAnchor)) {
    $postAnchor = 'if (url.pathname === "/api/mcp-day/session-customer/report") return wrap(await createMcpSessionCustomerReport(await readJsonBody(req)));'
  }
  if (-not $backend.Contains($postAnchor)) { Fail "POST route anchor not found" }
  $backend = $backend.Replace($postAnchor, $postAnchor + "`n  " + $postRoute)
  Write-Host "Inserted POST /api/mcp-settings/order-template" -ForegroundColor Green
} else {
  Write-Host "Order-template POST route already exists" -ForegroundColor Yellow
}

[System.IO.File]::WriteAllText($backendPath, $backend, $utf8NoBom)

$pageBase64 = "InVzZSBjbGllbnQiOwoKaW1wb3J0IHsgdXNlRWZmZWN0LCB1c2VNZW1vLCB1c2VTdGF0ZSwgdXNlVHJhbnNpdGlvbiB9IGZyb20gInJlYWN0IjsKaW1wb3J0IHsgUGFnZUhlYWRlciB9IGZyb20gIkAvdWkvbGF5b3V0L1BhZ2VIZWFkZXIiOwppbXBvcnQgeyBBcHBTaGVsbCB9IGZyb20gIkAvdWkvc2hlbGwvQXBwU2hlbGwiOwoKdHlwZSBSb3V0ZU9wdGlvbiA9IHsKICBpZDogc3RyaW5nOwogIG5hbWU6IHN0cmluZzsKICBhcmVhPzogc3RyaW5nOwogIHNhbGVzT3duZXI/OiBzdHJpbmc7CiAgc3RhdHVzPzogc3RyaW5nOwp9OwoKdHlwZSBUZW1wbGF0ZUl0ZW0gPSB7CiAgcHJvZHVjdE5hbWU6IHN0cmluZzsKICBxdWFudGl0eTogc3RyaW5nOwogIHVuaXRQcmljZTogc3RyaW5nOwogIHVuaXQ6IHN0cmluZzsKICBub3RlOiBzdHJpbmc7Cn07Cgp0eXBlIE9yZGVyVGVtcGxhdGUgPSB7CiAgaWQ/OiBzdHJpbmc7CiAgcm91dGVJZDogc3RyaW5nOwogIHRpdGxlOiBzdHJpbmc7CiAgbm90ZTogc3RyaW5nOwogIGl0ZW1zOiBUZW1wbGF0ZUl0ZW1bXTsKfTsKCnR5cGUgU2V0dGluZ3NQYXlsb2FkID0gewogIHJvdXRlczogUm91dGVPcHRpb25bXTsKICBzZWxlY3RlZFJvdXRlSWQ6IHN0cmluZzsKICB0ZW1wbGF0ZTogT3JkZXJUZW1wbGF0ZSB8IG51bGw7Cn07Cgpjb25zdCBlbXB0eUl0ZW0gPSAoKTogVGVtcGxhdGVJdGVtID0+ICh7CiAgcHJvZHVjdE5hbWU6ICIiLAogIHF1YW50aXR5OiAiMSIsCiAgdW5pdFByaWNlOiAiMCIsCiAgdW5pdDogIiIsCiAgbm90ZTogIiIKfSk7Cgpjb25zdCBlbXB0eVRlbXBsYXRlID0gKHJvdXRlSWQgPSAiIik6IE9yZGVyVGVtcGxhdGUgPT4gKHsKICByb3V0ZUlkLAogIHRpdGxlOiAiTeG6q3UgxJHGoW4gaMOgbmciLAogIG5vdGU6ICIiLAogIGl0ZW1zOiBbZW1wdHlJdGVtKCldCn0pOwoKZnVuY3Rpb24gdG9UZW1wbGF0ZUl0ZW1zKGl0ZW1zOiBUZW1wbGF0ZUl0ZW1bXSkgewogIHJldHVybiBpdGVtcwogICAgLm1hcCgoaXRlbSkgPT4gKHsKICAgICAgcHJvZHVjdE5hbWU6IGl0ZW0ucHJvZHVjdE5hbWUudHJpbSgpLAogICAgICBxdWFudGl0eTogTnVtYmVyKGl0ZW0ucXVhbnRpdHkgfHwgMCksCiAgICAgIHVuaXRQcmljZTogTnVtYmVyKGl0ZW0udW5pdFByaWNlIHx8IDApLAogICAgICB1bml0OiBpdGVtLnVuaXQudHJpbSgpLAogICAgICBub3RlOiBpdGVtLm5vdGUudHJpbSgpCiAgICB9KSkKICAgIC5maWx0ZXIoKGl0ZW0pID0+IGl0ZW0ucHJvZHVjdE5hbWUpOwp9Cgphc3luYyBmdW5jdGlvbiBmZXRjaFNldHRpbmdzKHJvdXRlSWQ/OiBzdHJpbmcpOiBQcm9taXNlPFNldHRpbmdzUGF5bG9hZD4gewogIGNvbnN0IHBhcmFtcyA9IG5ldyBVUkxTZWFyY2hQYXJhbXMoKTsKICBpZiAocm91dGVJZCkgcGFyYW1zLnNldCgicm91dGVJZCIsIHJvdXRlSWQpOwogIGNvbnN0IHJlc3BvbnNlID0gYXdhaXQgZmV0Y2goYC9hcGkvYmFja2VuZC9tY3Atc2V0dGluZ3Mvb3JkZXItdGVtcGxhdGUke3BhcmFtcy50b1N0cmluZygpID8gYD8ke3BhcmFtc31gIDogIiJ9YCwgewogICAgY2FjaGU6ICJuby1zdG9yZSIsCiAgICBoZWFkZXJzOiB7IEFjY2VwdDogImFwcGxpY2F0aW9uL2pzb24iIH0KICB9KTsKICBjb25zdCBwYXlsb2FkID0gYXdhaXQgcmVzcG9uc2UuanNvbigpLmNhdGNoKCgpID0+ICh7fSkpOwogIGlmICghcmVzcG9uc2Uub2spIHRocm93IG5ldyBFcnJvcihwYXlsb2FkLmVycm9yIHx8IHBheWxvYWQuZGV0YWlsIHx8ICJLaMO0bmcgdOG6o2kgxJHGsOG7o2MgY8OgaSDEkeG6t3QgbeG6q3UgxJHGoW4iKTsKICByZXR1cm4gcGF5bG9hZC5kYXRhIGFzIFNldHRpbmdzUGF5bG9hZDsKfQoKYXN5bmMgZnVuY3Rpb24gc2F2ZVNldHRpbmdzKHRlbXBsYXRlOiBPcmRlclRlbXBsYXRlKSB7CiAgY29uc3QgcmVzcG9uc2UgPSBhd2FpdCBmZXRjaCgiL2FwaS9iYWNrZW5kL21jcC1zZXR0aW5ncy9vcmRlci10ZW1wbGF0ZSIsIHsKICAgIG1ldGhvZDogIlBPU1QiLAogICAgY2FjaGU6ICJuby1zdG9yZSIsCiAgICBoZWFkZXJzOiB7IEFjY2VwdDogImFwcGxpY2F0aW9uL2pzb24iLCAiQ29udGVudC1UeXBlIjogImFwcGxpY2F0aW9uL2pzb24iIH0sCiAgICBib2R5OiBKU09OLnN0cmluZ2lmeSh7CiAgICAgIHJvdXRlSWQ6IHRlbXBsYXRlLnJvdXRlSWQsCiAgICAgIHRpdGxlOiB0ZW1wbGF0ZS50aXRsZSwKICAgICAgbm90ZTogdGVtcGxhdGUubm90ZSwKICAgICAgaXRlbXM6IHRvVGVtcGxhdGVJdGVtcyh0ZW1wbGF0ZS5pdGVtcykKICAgIH0pCiAgfSk7CiAgY29uc3QgcGF5bG9hZCA9IGF3YWl0IHJlc3BvbnNlLmpzb24oKS5jYXRjaCgoKSA9PiAoe30pKTsKICBpZiAoIXJlc3BvbnNlLm9rKSB0aHJvdyBuZXcgRXJyb3IocGF5bG9hZC5lcnJvciB8fCBwYXlsb2FkLmRldGFpbCB8fCAiS2jDtG5nIGzGsHUgxJHGsOG7o2MgbeG6q3UgxJHGoW4iKTsKICByZXR1cm4gcGF5bG9hZC5kYXRhOwp9CgpleHBvcnQgZGVmYXVsdCBmdW5jdGlvbiBNY3BTZXR0aW5nc1BhZ2UoKSB7CiAgY29uc3QgW3JvdXRlcywgc2V0Um91dGVzXSA9IHVzZVN0YXRlPFJvdXRlT3B0aW9uW10+KFtdKTsKICBjb25zdCBbc2VsZWN0ZWRSb3V0ZUlkLCBzZXRTZWxlY3RlZFJvdXRlSWRdID0gdXNlU3RhdGUoIiIpOwogIGNvbnN0IFt0ZW1wbGF0ZSwgc2V0VGVtcGxhdGVdID0gdXNlU3RhdGU8T3JkZXJUZW1wbGF0ZT4oZW1wdHlUZW1wbGF0ZSgpKTsKICBjb25zdCBbbWVzc2FnZSwgc2V0TWVzc2FnZV0gPSB1c2VTdGF0ZTxzdHJpbmcgfCBudWxsPihudWxsKTsKICBjb25zdCBbbG9hZGluZywgc3RhcnRMb2FkaW5nXSA9IHVzZVRyYW5zaXRpb24oKTsKICBjb25zdCBbc2F2aW5nLCBzdGFydFNhdmluZ10gPSB1c2VUcmFuc2l0aW9uKCk7CgogIGNvbnN0IHNlbGVjdGVkUm91dGUgPSB1c2VNZW1vKCgpID0+IHJvdXRlcy5maW5kKChyb3V0ZSkgPT4gcm91dGUuaWQgPT09IHNlbGVjdGVkUm91dGVJZCkgfHwgbnVsbCwgW3JvdXRlcywgc2VsZWN0ZWRSb3V0ZUlkXSk7CgogIGZ1bmN0aW9uIGxvYWQocm91dGVJZD86IHN0cmluZykgewogICAgc3RhcnRMb2FkaW5nKGFzeW5jICgpID0+IHsKICAgICAgdHJ5IHsKICAgICAgICBzZXRNZXNzYWdlKG51bGwpOwogICAgICAgIGNvbnN0IGRhdGEgPSBhd2FpdCBmZXRjaFNldHRpbmdzKHJvdXRlSWQpOwogICAgICAgIHNldFJvdXRlcyhkYXRhLnJvdXRlcyB8fCBbXSk7CiAgICAgICAgY29uc3QgcmVzb2x2ZWRSb3V0ZUlkID0gZGF0YS5zZWxlY3RlZFJvdXRlSWQgfHwgZGF0YS5yb3V0ZXM/LlswXT8uaWQgfHwgIiI7CiAgICAgICAgc2V0U2VsZWN0ZWRSb3V0ZUlkKHJlc29sdmVkUm91dGVJZCk7CiAgICAgICAgc2V0VGVtcGxhdGUoZGF0YS50ZW1wbGF0ZSB8fCBlbXB0eVRlbXBsYXRlKHJlc29sdmVkUm91dGVJZCkpOwogICAgICB9IGNhdGNoIChlcnJvcikgewogICAgICAgIHNldE1lc3NhZ2UoZXJyb3IgaW5zdGFuY2VvZiBFcnJvciA/IGVycm9yLm1lc3NhZ2UgOiAiS2jDtG5nIHThuqNpIMSRxrDhu6NjIGPDoGkgxJHhurd0Iik7CiAgICAgIH0KICAgIH0pOwogIH0KCiAgdXNlRWZmZWN0KCgpID0+IHsKICAgIGxvYWQoKTsKICB9LCBbXSk7CgogIGZ1bmN0aW9uIHNlbGVjdFJvdXRlKHJvdXRlSWQ6IHN0cmluZykgewogICAgc2V0U2VsZWN0ZWRSb3V0ZUlkKHJvdXRlSWQpOwogICAgbG9hZChyb3V0ZUlkKTsKICB9CgogIGZ1bmN0aW9uIHVwZGF0ZVRlbXBsYXRlKGZpZWxkOiAidGl0bGUiIHwgIm5vdGUiLCB2YWx1ZTogc3RyaW5nKSB7CiAgICBzZXRUZW1wbGF0ZSgoY3VycmVudCkgPT4gKHsgLi4uY3VycmVudCwgW2ZpZWxkXTogdmFsdWUgfSkpOwogIH0KCiAgZnVuY3Rpb24gdXBkYXRlSXRlbShpbmRleDogbnVtYmVyLCBmaWVsZDoga2V5b2YgVGVtcGxhdGVJdGVtLCB2YWx1ZTogc3RyaW5nKSB7CiAgICBzZXRUZW1wbGF0ZSgoY3VycmVudCkgPT4gKHsKICAgICAgLi4uY3VycmVudCwKICAgICAgaXRlbXM6IGN1cnJlbnQuaXRlbXMubWFwKChpdGVtLCBpdGVtSW5kZXgpID0+IGl0ZW1JbmRleCA9PT0gaW5kZXggPyB7IC4uLml0ZW0sIFtmaWVsZF06IHZhbHVlIH0gOiBpdGVtKQogICAgfSkpOwogIH0KCiAgZnVuY3Rpb24gYWRkSXRlbSgpIHsKICAgIHNldFRlbXBsYXRlKChjdXJyZW50KSA9PiAoeyAuLi5jdXJyZW50LCBpdGVtczogWy4uLmN1cnJlbnQuaXRlbXMsIGVtcHR5SXRlbSgpXSB9KSk7CiAgfQoKICBmdW5jdGlvbiByZW1vdmVJdGVtKGluZGV4OiBudW1iZXIpIHsKICAgIHNldFRlbXBsYXRlKChjdXJyZW50KSA9PiAoeyAuLi5jdXJyZW50LCBpdGVtczogY3VycmVudC5pdGVtcy5maWx0ZXIoKF8sIGl0ZW1JbmRleCkgPT4gaXRlbUluZGV4ICE9PSBpbmRleCkgfSkpOwogIH0KCiAgZnVuY3Rpb24gc3VibWl0KCkgewogICAgc3RhcnRTYXZpbmcoYXN5bmMgKCkgPT4gewogICAgICB0cnkgewogICAgICAgIHNldE1lc3NhZ2UobnVsbCk7CiAgICAgICAgY29uc3QgaXRlbXMgPSB0b1RlbXBsYXRlSXRlbXModGVtcGxhdGUuaXRlbXMpOwogICAgICAgIGlmICghdGVtcGxhdGUucm91dGVJZCAmJiAhc2VsZWN0ZWRSb3V0ZUlkKSB0aHJvdyBuZXcgRXJyb3IoIkPhuqduIGNo4buNbiB0dXnhur9uIik7CiAgICAgICAgaWYgKGl0ZW1zLmxlbmd0aCA9PT0gMCkgdGhyb3cgbmV3IEVycm9yKCJD4bqnbiBuaOG6rXAgw610IG5o4bqldCBt4buZdCBz4bqjbiBwaOG6qW0gbeG6q3UiKTsKICAgICAgICBjb25zdCByZXN1bHQgPSBhd2FpdCBzYXZlU2V0dGluZ3MoeyAuLi50ZW1wbGF0ZSwgcm91dGVJZDogdGVtcGxhdGUucm91dGVJZCB8fCBzZWxlY3RlZFJvdXRlSWQsIGl0ZW1zOiB0ZW1wbGF0ZS5pdGVtcyB9KTsKICAgICAgICBzZXRNZXNzYWdlKGDEkMOjIGzGsHUgbeG6q3UgxJHGoW4gJHtyZXN1bHQuaXRlbUNvdW50IHx8IGl0ZW1zLmxlbmd0aH0gc+G6o24gcGjhuqltYCk7CiAgICAgICAgbG9hZCh0ZW1wbGF0ZS5yb3V0ZUlkIHx8IHNlbGVjdGVkUm91dGVJZCk7CiAgICAgIH0gY2F0Y2ggKGVycm9yKSB7CiAgICAgICAgc2V0TWVzc2FnZShlcnJvciBpbnN0YW5jZW9mIEVycm9yID8gZXJyb3IubWVzc2FnZSA6ICJLaMO0bmcgbMawdSDEkcaw4bujYyBt4bqrdSDEkcahbiIpOwogICAgICB9CiAgICB9KTsKICB9CgogIHJldHVybiAoCiAgICA8QXBwU2hlbGwgYWN0aXZlSHJlZj0iL21jcCI+CiAgICAgIDxQYWdlSGVhZGVyCiAgICAgICAgZXllYnJvdz0iQ8OgaSDEkeG6t3QgdHV54bq/biIKICAgICAgICB0aXRsZT0iTeG6q3UgxJHGoW4gaMOgbmciCiAgICAgICAgc3VidGl0bGU9IlRoaeG6v3QgbOG6rXAgc+G6o24gcGjhuqltIG3huqt1IHRoZW8gdOG7q25nIHR1eeG6v24gxJHhu4MgZMO5bmcgbOG6oWkga2hpIHThuqFvIMSRxqFuIE1DUC4iCiAgICAgIC8+CgogICAgICA8c2VjdGlvbiBjbGFzc05hbWU9ImNhcmQiPgogICAgICAgIDxkaXYgY2xhc3NOYW1lPSJzZWN0aW9uLWhlYWRpbmciPgogICAgICAgICAgPGRpdj4KICAgICAgICAgICAgPGgyIGNsYXNzTmFtZT0icGFuZWwtdGl0bGUiPk3huqt1IMSRxqFuIHRoZW8gdHV54bq/bjwvaDI+CiAgICAgICAgICAgIDxwIGNsYXNzTmFtZT0icGFnZS1zdWJ0aXRsZSI+TeG7mXQgdHV54bq/biBjw7MgbeG7mXQgbeG6q3UgxJHGoW4gxJFhbmcgaG/huqF0IMSR4buZbmcuIE3huqt1IG7DoHkgY2jGsGEgdOG7sSDDoXAgdsOgbyBwb3B1cCDEkcahbiBjaG8gdOG7m2kgZ2F0ZSB0aeG6v3AgdGhlby48L3A+CiAgICAgICAgICA8L2Rpdj4KICAgICAgICAgIDxidXR0b24gY2xhc3NOYW1lPSJidXR0b24gcHJpbWFyeSIgdHlwZT0iYnV0dG9uIiBvbkNsaWNrPXtzdWJtaXR9IGRpc2FibGVkPXtzYXZpbmcgfHwgbG9hZGluZ30+CiAgICAgICAgICAgIHtzYXZpbmcgPyAixJBhbmcgbMawdS4uLiIgOiAiTMawdSBt4bqrdSDEkcahbiJ9CiAgICAgICAgICA8L2J1dHRvbj4KICAgICAgICA8L2Rpdj4KCiAgICAgICAgPGRpdiBjbGFzc05hbWU9ImdyaWQiPgogICAgICAgICAgPGxhYmVsIGNsYXNzTmFtZT0iZm9ybS1maWVsZCI+CiAgICAgICAgICAgIDxzbWFsbD5DaOG7jW4gdHV54bq/bjwvc21hbGw+CiAgICAgICAgICAgIDxzZWxlY3QgdmFsdWU9e3NlbGVjdGVkUm91dGVJZH0gb25DaGFuZ2U9eyhldmVudCkgPT4gc2VsZWN0Um91dGUoZXZlbnQudGFyZ2V0LnZhbHVlKX0gZGlzYWJsZWQ9e2xvYWRpbmcgfHwgc2F2aW5nfT4KICAgICAgICAgICAgICB7cm91dGVzLm1hcCgocm91dGUpID0+ICgKICAgICAgICAgICAgICAgIDxvcHRpb24ga2V5PXtyb3V0ZS5pZH0gdmFsdWU9e3JvdXRlLmlkfT57cm91dGUubmFtZX08L29wdGlvbj4KICAgICAgICAgICAgICApKX0KICAgICAgICAgICAgPC9zZWxlY3Q+CiAgICAgICAgICA8L2xhYmVsPgoKICAgICAgICAgIDxkaXYgY2xhc3NOYW1lPSJtZXRyaWMtcm93Ij4KICAgICAgICAgICAgPHNwYW4+VHV54bq/biDEkWFuZyBjaOG7jW48L3NwYW4+CiAgICAgICAgICAgIDxzdHJvbmc+e3NlbGVjdGVkUm91dGUgPyBgJHtzZWxlY3RlZFJvdXRlLm5hbWV9IMK3ICR7c2VsZWN0ZWRSb3V0ZS5hcmVhIHx8ICItIn1gIDogIkNoxrBhIGNo4buNbiJ9PC9zdHJvbmc+CiAgICAgICAgICA8L2Rpdj4KCiAgICAgICAgICA8bGFiZWwgY2xhc3NOYW1lPSJmb3JtLWZpZWxkIj4KICAgICAgICAgICAgPHNtYWxsPlTDqm4gbeG6q3U8L3NtYWxsPgogICAgICAgICAgICA8aW5wdXQgdmFsdWU9e3RlbXBsYXRlLnRpdGxlfSBvbkNoYW5nZT17KGV2ZW50KSA9PiB1cGRhdGVUZW1wbGF0ZSgidGl0bGUiLCBldmVudC50YXJnZXQudmFsdWUpfSBwbGFjZWhvbGRlcj0iVkQ6IE3huqt1IMSRxqFuIHRyw6Agc+G7r2EgdHV54bq/biBUaOG7qSA2IiAvPgogICAgICAgICAgPC9sYWJlbD4KCiAgICAgICAgICA8bGFiZWwgY2xhc3NOYW1lPSJmb3JtLWZpZWxkIj4KICAgICAgICAgICAgPHNtYWxsPkdoaSBjaMO6IG3huqt1PC9zbWFsbD4KICAgICAgICAgICAgPHRleHRhcmVhIHZhbHVlPXt0ZW1wbGF0ZS5ub3RlfSBvbkNoYW5nZT17KGV2ZW50KSA9PiB1cGRhdGVUZW1wbGF0ZSgibm90ZSIsIGV2ZW50LnRhcmdldC52YWx1ZSl9IHBsYWNlaG9sZGVyPSJHaGkgY2jDuiBjw6FjaCBkw7luZyBt4bqrdSAvIG5ow7NtIGtow6FjaCAvIMSRaeG7gXUga2nhu4duIMOhcCBk4bulbmciIC8+CiAgICAgICAgICA8L2xhYmVsPgogICAgICAgIDwvZGl2PgoKICAgICAgICA8ZGl2IGNsYXNzTmFtZT0ibWNwLWxpbmUtbGlzdCI+CiAgICAgICAgICB7dGVtcGxhdGUuaXRlbXMubWFwKChpdGVtLCBpbmRleCkgPT4gKAogICAgICAgICAgICA8ZGl2IGNsYXNzTmFtZT0idmlzaXQtZm9jdXMtY2FyZCIga2V5PXtgdGVtcGxhdGUtaXRlbS0ke2luZGV4fWB9PgogICAgICAgICAgICAgIDxzcGFuPlPhuqNuIHBo4bqpbSBt4bqrdSB7aW5kZXggKyAxfTwvc3Bhbj4KICAgICAgICAgICAgICA8bGFiZWwgY2xhc3NOYW1lPSJmb3JtLWZpZWxkIj48c21hbGw+VMOqbiBz4bqjbiBwaOG6qW08L3NtYWxsPjxpbnB1dCB2YWx1ZT17aXRlbS5wcm9kdWN0TmFtZX0gb25DaGFuZ2U9eyhldmVudCkgPT4gdXBkYXRlSXRlbShpbmRleCwgInByb2R1Y3ROYW1lIiwgZXZlbnQudGFyZ2V0LnZhbHVlKX0gcGxhY2Vob2xkZXI9IlZEOiBUcsOgIHPhu69hIHRydXnhu4FuIHRo4buRbmciIC8+PC9sYWJlbD4KICAgICAgICAgICAgICA8bGFiZWwgY2xhc3NOYW1lPSJmb3JtLWZpZWxkIj48c21hbGw+U+G7kSBsxrDhu6NuZyBt4bq3YyDEkeG7i25oPC9zbWFsbD48aW5wdXQgaW5wdXRNb2RlPSJkZWNpbWFsIiB2YWx1ZT17aXRlbS5xdWFudGl0eX0gb25DaGFuZ2U9eyhldmVudCkgPT4gdXBkYXRlSXRlbShpbmRleCwgInF1YW50aXR5IiwgZXZlbnQudGFyZ2V0LnZhbHVlKX0gLz48L2xhYmVsPgogICAgICAgICAgICAgIDxsYWJlbCBjbGFzc05hbWU9ImZvcm0tZmllbGQiPjxzbWFsbD5HacOhIG3hurdjIMSR4buLbmg8L3NtYWxsPjxpbnB1dCBpbnB1dE1vZGU9ImRlY2ltYWwiIHZhbHVlPXtpdGVtLnVuaXRQcmljZX0gb25DaGFuZ2U9eyhldmVudCkgPT4gdXBkYXRlSXRlbShpbmRleCwgInVuaXRQcmljZSIsIGV2ZW50LnRhcmdldC52YWx1ZSl9IC8+PC9sYWJlbD4KICAgICAgICAgICAgICA8bGFiZWwgY2xhc3NOYW1lPSJmb3JtLWZpZWxkIj48c21hbGw+xJDGoW4gduG7izwvc21hbGw+PGlucHV0IHZhbHVlPXtpdGVtLnVuaXR9IG9uQ2hhbmdlPXsoZXZlbnQpID0+IHVwZGF0ZUl0ZW0oaW5kZXgsICJ1bml0IiwgZXZlbnQudGFyZ2V0LnZhbHVlKX0gcGxhY2Vob2xkZXI9Imx5IC8gZ8OzaSAvIHRow7luZyIgLz48L2xhYmVsPgogICAgICAgICAgICAgIDxsYWJlbCBjbGFzc05hbWU9ImZvcm0tZmllbGQiPjxzbWFsbD5HaGkgY2jDuiBkw7JuZzwvc21hbGw+PGlucHV0IHZhbHVlPXtpdGVtLm5vdGV9IG9uQ2hhbmdlPXsoZXZlbnQpID0+IHVwZGF0ZUl0ZW0oaW5kZXgsICJub3RlIiwgZXZlbnQudGFyZ2V0LnZhbHVlKX0gcGxhY2Vob2xkZXI9IkdoaSBjaMO6IHJpw6puZyBjaG8gc+G6o24gcGjhuqltIiAvPjwvbGFiZWw+CiAgICAgICAgICAgICAge3RlbXBsYXRlLml0ZW1zLmxlbmd0aCA+IDEgPyA8YnV0dG9uIGNsYXNzTmFtZT0iYnV0dG9uIiB0eXBlPSJidXR0b24iIG9uQ2xpY2s9eygpID0+IHJlbW92ZUl0ZW0oaW5kZXgpfSBkaXNhYmxlZD17c2F2aW5nfT5Yw7NhIHPhuqNuIHBo4bqpbTwvYnV0dG9uPiA6IG51bGx9CiAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgKSl9CiAgICAgICAgPC9kaXY+CgogICAgICAgIDxkaXYgY2xhc3NOYW1lPSJzaGVldC1hY3Rpb24tZ3JpZCI+CiAgICAgICAgICA8YnV0dG9uIGNsYXNzTmFtZT0iYnV0dG9uIiB0eXBlPSJidXR0b24iIG9uQ2xpY2s9e2FkZEl0ZW19IGRpc2FibGVkPXtzYXZpbmd9PlRow6ptIHPhuqNuIHBo4bqpbSBt4bqrdTwvYnV0dG9uPgogICAgICAgICAgPGJ1dHRvbiBjbGFzc05hbWU9ImJ1dHRvbiBwcmltYXJ5IiB0eXBlPSJidXR0b24iIG9uQ2xpY2s9e3N1Ym1pdH0gZGlzYWJsZWQ9e3NhdmluZyB8fCBsb2FkaW5nfT57c2F2aW5nID8gIsSQYW5nIGzGsHUuLi4iIDogIkzGsHUgbeG6q3UgxJHGoW4ifTwvYnV0dG9uPgogICAgICAgIDwvZGl2PgoKICAgICAgICB7bWVzc2FnZSA/IDxwIGNsYXNzTmFtZT0icGFnZS1zdWJ0aXRsZSI+e21lc3NhZ2V9PC9wPiA6IG51bGx9CiAgICAgIDwvc2VjdGlvbj4KICAgIDwvQXBwU2hlbGw+CiAgKTsKfQo="
$pageBytes = [Convert]::FromBase64String($pageBase64)
[System.IO.File]::WriteAllBytes($pagePath, $pageBytes)
Write-Host "Wrote settings page from UTF-8 base64 payload" -ForegroundColor Green

Write-Host ""
Write-Host "Building..." -ForegroundColor Cyan
npm run build
if ($LASTEXITCODE -ne 0) {
  Fail "Build failed. Do not commit/push. Send full build log."
}

Write-Host ""
Write-Host "BUILD OK" -ForegroundColor Green

if ($CommitAndPush) {
  Write-Host ""
  Write-Host "Committing and pushing..." -ForegroundColor Cyan
  git add apps/backend/server.js src/app/mcp/settings/page.tsx supabase/migrations/20260705_mcp_route_order_template_contract.sql
  git commit -m "feat: add route order template settings"
  if ($LASTEXITCODE -ne 0) { Fail "git commit failed. Send git status --short." }
  git push origin main
  if ($LASTEXITCODE -ne 0) { Fail "git push failed. Send log." }
  Write-Host ""
  Write-Host "PUSH DONE. Run pullmcp on VPS after this." -ForegroundColor Green
} else {
  Write-Host ""
  Write-Host "Not committed yet. To commit and push automatically, run:" -ForegroundColor Yellow
  Write-Host 'powershell -ExecutionPolicy Bypass -File .\patch-mcp-route-order-template-settings.ps1 -CommitAndPush' -ForegroundColor Yellow
}
